on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '0 9 * * MON' # Run at 9:00 AM UTC every Monday

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: "linux/arm64,linux/amd64"
          push: true
          # could probably push a date tag since we run on cron too
          tags: "ghcr.io/${{ github.repository }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
